name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build-website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
