/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("models/id-card.glb");
  return (
    <group
      scale={2}
      position={[0, -2.5, 0]}
      rotation={[0, -Math.PI / 2, 0]}
      {...props}
      dispose={null}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clip.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clamp.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.card.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("models/id-card.glb");
